model:
  hidden_dims: [32, 16, 8]
  learning_rate: 1e-5
  epochs: 1000

data:
  dataset: get_moons # get_moons OR get_circles OR get_data
  test_size: 0.3
  n_samples: 10000
  noise: 0.2
  n_features: 5
  n_redundant: 0
  n_informative: 5
  n_clusters_per_class: 1
  n_classes: 3
  seed: 1337
